name: Assign Publish

on:
  workflow_dispatch:
    inputs:
      workspace:
        description: "working directory"
        required: true

permissions:
  contents: read
  packages: write

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: pnpm install
      - run: pnpm run build
        working-directory: ${{ github.event.inputs.workspace }}
      - run: npm publish --access public
        working-directory: ${{ github.event.inputs.workspace }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NEXTSTAR_NPM_TOKEN }}
  github-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
      - run: pnpm install
      - run: pnpm run build
        working-directory: ${{ github.event.inputs.workspace }}
      - run: npm publish
        working-directory: ${{ github.event.inputs.workspace }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
